[package]
name = "sprite_shrink_cd"
version = "0.1.0"
edition = "2024"
publish = true
license = "MPL-2.0"

[lib]
name = "sprite_shrink_cd"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
sprite_shrink = {path = "../lib_sprite_shrink"}

crc = "3.4.0"
once_cell = "1.21"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[build-dependencies]
cbindgen = "0.29"
